language: csharp

services:
  - docker

sudo: required

before_install:
  - docker pull dcurylo/fsharp-mono-netcore:2.1.503
  - chmod 755 ./*.sh

jobs:
  include:
    - stage: "CI"
      script: docker run -v "${pwd}:/var/fantomas" -w "/var/fantomas" dcurylo/fsharp-mono-netcore:2.1.503  bash -c "./install.sh ; ./build.sh"
    - stage: "TestExternalProjects"
      script: docker run -v "${pwd}:/var/fantomas" -w "/var/fantomas" dcurylo/fsharp-mono-netcore:2.1.503  bash -c "./install.sh ; ./build.sh -t TestExternalProjects" 
      if: branch = test-external-projects
