language: csharp
dotnet: 2.1.503
mono: 
  - latest

sudo: required

before_install:
  - ls -la
  - chmod a+x ./install.sh
install:
  - ./install.sh

jobs:
  include:
    - stage: "CI"
      script: ./build.sh All
    - stage: "TestExternalProjects"
      script: ./build.sh -t TestExternalProjects
      if: branch = test-external-projects
